# -*- coding: utf-8 -*-
"""Copy of TCN_Example_Bahareh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TcSy2-BXUmAPwJeWSyDy84Wq6-ZWfR-5
"""

from cProfile import label
import multiprocessing
import os
import sys
from tabnanny import check
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="3"
import tensorflow as tf
import scipy
import h5py
import glob, os
from scipy.io import loadmat
import math
from keras.models import Model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
import collections
# from parse_label import parse_event_labels
# %matplotlib inline
# from keras.datasets import mnist
from sklearn.metrics import plot_precision_recall_curve,roc_curve,roc_auc_score,auc
from sklearn.metrics import precision_recall_fscore_support,precision_recall_curve
import itertools
from tensorflow import keras
from tensorflow.keras.regularizers import l2, l1_l2
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D, GlobalAveragePooling2D
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,TimeDistributed, GRU,Concatenate
from tensorflow.keras.optimizers import Adam
from keras.layers import BatchNormalization
from keras.utils import np_utils
from keras.layers import Conv1D, GlobalAveragePooling1D,MaxPooling1D,AveragePooling1D
from keras.layers.advanced_activations import LeakyReLU
from keras.preprocessing.image import ImageDataGenerator
from sklearn import preprocessing
from keras import regularizers
from numpy import mean
from numpy import std
from tqdm.auto import tqdm
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from tensorflow.keras.datasets import cifar10
# from keras.optimizers import Adam
# from keras.layers.normalization import BatchNormalization
from keras.utils import np_utils
from keras.layers import Conv1D, MaxPooling1D, ZeroPadding1D, GlobalAveragePooling1D,Bidirectional
from keras.layers.advanced_activations import LeakyReLU
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import LearningRateScheduler
from sklearn import preprocessing
from sklearn.metrics import roc_auc_score
# from keras import regularizers
# from regularizers import l1_l2
from numpy import mean
from numpy import std
import pickle
import re
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.layers import InputLayer
from keras.layers import Input
import time
import gc
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator
import math
import wandb
from wandb.keras import WandbCallback
from collections import deque
from scipy.io import loadmat
import copy

# datagen = ImageDataGenerator(zca_whitening=True)
# from google.colab import drive
# drive.mount('/content/drive')

from keras_tcn import TCN
from SBRNN_Keras import ModelConfig, SBRNN_Detector, ModelConfigTCN
from data_gen_chb import SeizureDataGenerator


def PatientsName():

  Name=['chb01','chb02','chb03','chb04','chb05','chb06','chb07','chb08','chb09','chb10',
  'chb11','chb12','chb13','chb14','chb15','chb16','chb17','chb18','chb19','chb20','chb21',
  'chb22','chb23','chb24']
  return Name

def segment_data(loaddir):

  
  info_mat = loadmat(loaddir)

  # data = info_mat['data']
  DenoisedSig = info_mat['DenoisedSig']
  # DenoisedSigSeizure = info_mat['DenoisedSigSeizure']

  #print("shape of data is ", data.shape)
  # print("shape of DenoisedSig is ", DenoisedSig.shape)


  SigEnd = info_mat['Sig_end'][0][0]
  SigStart = info_mat['Sig_start'][0][0]
  SiezureStart = info_mat['Siezure_start'][0][0]
  SiezureEnd = info_mat['Siezure_end'][0][0]
  n_channels = 18
  Fs = 256

  data_denoised = DenoisedSig[:,0:DenoisedSig.shape[1]-1]

  # n = data_denoised.shape[1]//Fs

  output=[data_denoised[:,i:i + Fs] for i in range(0,data_denoised.shape[1], Fs)]

  X = np.array(output)
  print("out shape", X.shape)

  Ylabel=np.zeros((SigEnd-SigStart,1))
  Seizure_durarion = SiezureEnd - SiezureStart + 1

  Seizure_start_label = SiezureStart - SigStart 
  #print(Seizure_start_label)
  Ylabel[Seizure_start_label:Seizure_start_label+Seizure_durarion,0] =  1

  return X, Ylabel



def PatientsEDFFile(dirname):

  os.chdir(dirname)
  a=[]
  X=[]
  Y=[]
  b=[]
  c = []
  k=0
  for file in glob.glob("*.mat"):
    # print("this is file",file)
    split_file=file.split('.')
    # print(split_file[0])
    # split_file2=split_file[0].split('_')
    # b.append(split_file2[2]+'_'+split_file2[3]+'_'+split_file2[4]+'_'+split_file2[5])
    a.append(file)
    c.append(split_file[0])

      # print(a)
  return a,c
  
def recall2(y_true, y_pred):

  true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
  possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
  recall_m = true_positives / (possible_positives + K.epsilon())
  return recall_m

def precision(y_true, y_pred):

  true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
  predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
  precision_m = true_positives / (predicted_positives + K.epsilon())
  return precision_m

def AUCPR(y_true, y_pred):

  precision, recall, _ = precision_recall_curve(y_true, y_pred)

  PR1=auc(recall, precision)

  return PR1
# def f1_score(y_true, y_pred):
  # precision_m = precision(y_true, y_pred)
  # recall_m = recall(y_true, y_pred)
  # return 2*((precision_m*recall_m)/(precision_m+recall_m+K.epsilon()))
def f1_score(y_true, y_pred,threshold_shift=0):

  y_pred = K.clip(y_pred, 0, 1)
  # shifting the prediction threshold from .5 if needed
  y_pred_bin = K.round(y_pred + threshold_shift)
  tp = K.sum(K.round(y_true * y_pred_bin)) + K.epsilon()
  fp = K.sum(K.round(K.clip(y_pred_bin - y_true, 0, 1)))
  fn = K.sum(K.round(K.clip(y_true - y_pred, 0, 1)))
  precision1 = tp / (tp + fp)
  recall1 = tp / (tp + fn)
  p = precision1
  r = recall1
  return 2 * ((p * r) / (p + r))

def auc_roc(y_true, y_pred):

  return tf.py_function(roc_auc_score, (y_true, y_pred), tf.double)

def auc_pr(y_true, y_pred):

  return tf.py_function(AUCPR, (y_true, y_pred), tf.double)


def  Conv_BN_Act_Pool(filtNo,filtsize1,filtsize2,input1,activation,PoolSize,l2_size,drop_size):


  conv1 = Conv1D(filtNo,filtsize1,kernel_regularizer=l2(l2_size))(input1)
  conv2 = Conv1D(filtNo, filtsize2,kernel_regularizer=l2(l2_size))(conv1)
  BN=BatchNormalization(axis=-1)(conv2)
  ActFunc=Activation(activation)(BN)
  pool1=MaxPooling1D(pool_size=PoolSize)(ActFunc)
  # out=Dropout(drop_size)(pool1)

  return pool1

def define_CNN(drop_size,initLR):
  l2_size=None
  input_shape=(1000,20)
  denseSize=8
  activation='relu'
  filtsize1=22
  filtNo1=8
  filtsize2=10
  filtNo2=16
  PoolSize=2
  input1 = Input(input_shape)
  model1=Conv_BN_Act_Pool(filtNo1,filtsize2,filtsize1,input1,activation,PoolSize,l2_size,drop_size)
  model2=Conv_BN_Act_Pool(filtNo1,filtsize2,filtsize1,model1,activation,PoolSize,l2_size,drop_size)
  model3=Conv_BN_Act_Pool(filtNo1,filtsize2,filtsize1,model2,activation,PoolSize,l2_size,drop_size)
  model4=Conv_BN_Act_Pool(filtNo2,filtsize2,filtsize1,model3,activation,PoolSize,l2_size,drop_size)
  model5=Conv_BN_Act_Pool(filtNo2,filtsize2,filtsize1,model4,activation,PoolSize,l2_size,drop_size)
  conv6=Conv1D(filtNo1,1)(model5)
  drop1=Dropout(0.25)(conv6)
  flat=Flatten()(drop1)

  denseout = Dense(100)(flat)
  denseout2 = Dense(50)(denseout)
  drop2=Dropout(0.5)(denseout2)
  output = Dense(1, activation='sigmoid')(drop2)
  # define a model with a list of two inputs
  model = Model(inputs=input1, outputs=output)
  model.compile(optimizer=Adam(learning_rate=initLR),loss='binary_crossentropy',metrics=["accuracy",f1_score,auc_roc,precision,recall2,auc_pr])

  return model

def MeanStdVar(mylist):


  ListMean=np.mean(mylist,axis=0)
  ListStd=np.std(mylist)
  ListVar=np.var(mylist)

  return ListMean,ListStd,ListVar

def lr_exp_decay(epoch, lr):
  # k = math.sqrt(2)
  k=2
  if epoch<100:
    return lr
  elif lr>0.00001 & epoch>100:
    return lr / k

def ReadMatFiles(dirname,dir_csv,ind,category_name):

  EDF = []
  EDFFiles = []
  Name = []
  EDF,names = PatientsEDFFile(dirname)
  Name = PatientsName()
  Xfile=[]
  Yfile=[]
  c = 0


  X=[]
  Y=[]

  # print(ind)
  for k in range(len(ind)):

  
    csv_name = EDF[ind[k]].split('.')
    x, y = segment_data(os.path.join(dirname,EDF[ind[k]]))

    print("shape of x",x.shape)
    print("shape of y", y.shape)
    # path = os.path.join(dirname,EDF[ind[k]])

    df = pd.DataFrame(columns=['FileName', 'Label', 'index'])
    for j in range(x.shape[0]):
      df = df.append({'FileName':x , 'Label': y[j,:][0],'index': np.int64(j)},ignore_index=True)
    df.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_chb/{category_name}'), f'{csv_name[0]}.pkl'))
    c = c + len(df) - 7
  
  print("this is the whole length", c)

    # X.append(x)
    # Y.append(y)
    #matfile=loadmat(os.path.join(dirname,EDF[ind[k]]))

  
  # X = np.concatenate(X,axis=0)
  # Y = np.concatenate(Y,axis=0)
  # Y = Y.T
  # print(X.shape)
  # print(Y.shape)
  # return X, Y

def SelectIndx(EDFNo,ind,dirname):

  EDF=[]
  EDFFiles=[]
  Name=[]
  EDF,names=PatientsEDFFile(dirname)
  Name=PatientsName()

  indx=[]
  for j in range(len(ind)):
    # print(j)
    indices = [i for i, elem in enumerate(EDF) if Name[j] in elem]
    indx.append(indices)

  indtest=[]
  indtrain=[]
  for i in range(len(indx)):

    for k in range(len(indx[i])):
      # print(len(indx[i]))

      if k==EDFNo:
        indtest.append(indx[i][k])
        # print(indtest)

      else:
        indtrain.append(indx[i][k])
        # print(indtrain)

  # indtest=np.concatenate(indtest,axis=0)
  # indtrain=np.concatenate(indtrain,axis=0)
  # print(len(indtest))
  return indtest,indtrain



## The code for training TCN
def TCN_Model(len_seq, one_sec_samp, num_channel, num_filters, LR):

  seq_len = len_seq

  input_size = one_sec_samp

  num_chan = num_channel

  inps = keras.layers.Input(shape=(seq_len, num_chan, input_size), name="inp")

  n = seq_len*2
  a = [i for i in range(1, n+1) if (math.log(i)/math.log(2)).is_integer()]
  dilation_list = tuple(a)

  tcn_out = TCN(nb_filters=num_filters, kernel_size=3,
                        nb_stacks=1, dilations=dilation_list,
                        padding='same', use_skip_connections=True,
                        dropout_rate=0.2, return_sequences=True,
                        activation='wavenet')(inps)

  #latent_large = Flatten()(tcn_out)
  #tcn_out = keras.layers.Lambda(lambda x: x[:, :, 0, :])(tcn_out)
  shape = tcn_out.get_shape().as_list()
  print(shape)
  tcn_out = tf.reshape(tcn_out, [-1, shape[1] , shape[2] * shape[3]])
  latent_small = TimeDistributed(Dense(128,activation='relu'))(tcn_out)
  probs = TimeDistributed(Dense(1,activation='sigmoid'))(latent_small)
  preds = tf.cast(probs > 0.5, tf.int16)

  model = keras.models.Model(inputs=inps, outputs=probs)
  model.compile(loss='binary_crossentropy', optimizer=keras.optimizers.Adam(learning_rate=LR), metrics=["accuracy",f1_score,precision,recall2])
  #print(model)
  return model



def lr_exp_decay(epoch, lr):
  # k = math.sqrt(2)
  k=2

  if lr>0.00001:
    return lr / k
  
  else:
    return lr


def file_generator(data_path,data_files,temporal_length,temporal_stride):

  '''
  data_files - list of csv files to be read.
  '''
  for f in data_files:
    # read all the csv files (one csv file corresponds to one vdieo) in data_files one by one
    # tmp_df = pd.read_csv(os.path.join(data_path,f))
    tmp_df = pd.read_pickle(os.path.join(data_path,f))
    label_list = list(tmp_df['Label'])  # Load all the labels in the label_list
    index_list = list(tmp_df['index'])
    total_images = len(label_list)
    if total_images >= temporal_length: # only if the number of frames in the video is greater tha temporal length, use that video
      num_samples = int((total_images-temporal_length)/temporal_stride)+1
      print ('num of samples from vid seq-{}: {}'.format(f,num_samples))
      img_list = list(tmp_df['FileName'])
    else: # if the number of frames are less than temporal length , discard it
      print ('num of frames is less than temporal length; hence discarding this file-{}'.format(f))
      continue

    start_frame = 0
    samples = deque() # initliaze a queue to store the frames
    labels = deque()
    indices = deque()
    samp_count=0 # a counter to count the number of smaple. one smaple has as many frames as defined by temporal length
    for j  in range(len(img_list)):
      array_test = np.array(img_list[j])
      print(img_list[j].shape)
      samples.append(array_test[index_list[j]])
      labels.append(label_list[j])
      indices.append(index_list[j])
      if len(samples)==temporal_length:
        #if the queue has as many frames as temporal length, return it as one sample

        samples_c = copy.deepcopy(samples)
        lables_c = copy.deepcopy(labels) # copy the queue as in the next stage frames would be popped
        indices_c = copy.deepcopy(indices)
        samp_count+=1

        for t in range(temporal_stride): # pop out as many frames as described by the stride from the left to accomodate new frames
          samples.popleft()
          labels.popleft()
          indices_c.pop
          # print(list(indices_c).pop(0))

        yield list(samples_c), list(lables_c), list(indices_c)[-temporal_length:]# return a sample(consisting of as many frames as defined by temporal length)
                                          # and its corsponding label

def file_generator_v2(data_path,data_files,temporal_length,temporal_stride):

  '''
  data_files - list of csv files to be read.
  '''
  f = data_files
  # read all the csv files (one csv file corresponds to one vdieo) in data_files one by one
  # tmp_df = pd.read_csv(os.path.join(data_path,f))
  tmp_df = pd.read_pickle(os.path.join(data_path,f))
  label_list = list(tmp_df['Label'])  # Load all the labels in the label_list
  index_list = list(tmp_df['index'])
  total_images = len(label_list)
  if total_images >= temporal_length: # only if the number of frames in the video is greater tha temporal length, use that video
    num_samples = int((total_images-temporal_length)/temporal_stride)+1
    print ('num of samples from vid seq-{}: {}'.format(f,num_samples))
    img_list = list(tmp_df['FileName'])
  else: # if the number of frames are less than temporal length , discard it
    print ('num of frames is less than temporal length; hence discarding this file-{}'.format(f))
    # continue

  start_frame = 0
  samples = deque() # initliaze a queue to store the frames
  labels = deque()
  indices = deque()
  samp_count=0 # a counter to count the number of smaple. one smaple has as many frames as defined by temporal length
  for j  in range(len(img_list)):
    array_test = np.array(img_list[j])
    print(img_list[j].shape)
    samples.append(array_test[index_list[j]])
    labels.append(label_list[j])
    indices.append(index_list[j])
    if len(samples)==temporal_length:
      #if the queue has as many frames as temporal length, return it as one sample

      samples_c = copy.deepcopy(samples)
      lables_c = copy.deepcopy(labels) # copy the queue as in the next stage frames would be popped
      indices_c = copy.deepcopy(indices)
      samp_count+=1

      for t in range(temporal_stride): # pop out as many frames as described by the stride from the left to accomodate new frames
        samples.popleft()
        labels.popleft()
        indices_c.pop
        # print(list(indices_c).pop(0))

      yield list(samples_c), list(lables_c), list(indices_c)[-temporal_length:]# return a sample(consisting of as many frames as defined by temporal length)
                                        # and its corsponding label

def shuffle_data(samples):

  data = shuffle(samples)
  return data

def load_samples_modified(dir_csv,data_cat,data_list,temporal_length,temporal_stride,shuffle=True):

  data_path = os.path.join(dir_csv,f'data_files_chb/{data_cat}')
  data_csv_list = os.listdir(data_path)

  if shuffle:
    data_csv_list = shuffle_data(data_csv_list)
  
  # print(os.path.join(data_path,data_shuffle[0]))
  data_files = data_csv_list#[0:num_csv]
  print("this is data files",data_files)
  # define a generator to read the samples
  file_gen = file_generator(data_path,data_files,temporal_length,temporal_stride)
  iterator = True
  data_list = []
  df = pd.DataFrame(columns=['FileName', 'Label', 'index'])
  while iterator:
      try:
          x, y, index = next(file_gen)
          # x = segment_data(x[0])
          x = np.array(x)
          # print("this is len of x",len(x[1]))
          print(x.shape)
          # x = x[index]
          df = df.append({'FileName': x, 'Label': y,'index': index},ignore_index=True)
          # x=list(x)
          # data_list.append([x,y,index])

      except Exception as e:
          print ('the exception: ',e)
          iterator = False
          print ('end of data generator')
  df.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_chb/train/train_list'), 'data_list.pkl'))

  # return data_list

def load_samples_modified_V2_seperate(dir_csv,data_cat,data_list,temporal_length,temporal_stride,shuffle=True):

  data_path = os.path.join(dir_csv,f'data_files_chb/{data_cat}')
  print(data_path)
  data_csv_list = os.listdir(data_path)

  if shuffle:
    data_csv_list = shuffle_data(data_csv_list)
  
  # print(os.path.join(data_path,data_shuffle[0]))
  data_files = data_csv_list#[0:num_csv]
  
  os.chdir(data_path)
  data_files = glob.glob('*.pkl')
  print("this is data files", data_files[0])
  # define a generator to read the samples
  for i in range(len(data_files)):

    file_gen = file_generator_v2(data_path,data_files[i],temporal_length,temporal_stride)
    iterator = True
    data_list = []
    df = pd.DataFrame(columns=['FileName', 'Label', 'index'])
    while iterator:
        try:
            x, y, index = next(file_gen)
            # x = segment_data(x[0])
            x = np.array(x)
            # print("this is len of x",len(x[1]))
            print(x.shape)
            # x = x[index]
            df = df.append({'FileName': x, 'Label': y,'index': index},ignore_index=True)
            # x=list(x)
            # data_list.append([x,y,index])

        except Exception as e:
            print ('the exception: ',e)
            iterator = False
            print ('end of data generator')
    df.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_chb/train/train_list_v2'), data_files[i]))
 

#################### Train the model #############################


modelname = 'TCN_CHB_MIT'
initLR = 0.001
num_epochs = 10
batch_size = 256

len_seq = 8
one_sec_samp = 256
num_channel = 18
num_filters = 16
LR = 0.001
tcn = 1
cnn = 0
two_dcnn = 0
gru = 0
len_seq_gru = 3

indx=range(0,24)

# print(model_tcn)

dir_csv = '/home/baharsalafian'
if not os.path.exists(os.path.join(dir_csv,'data_files_chb')):
    os.mkdir(os.path.join(dir_csv,'data_files_chb'))
if not os.path.exists(os.path.join(dir_csv,'data_files_chb/train')):
    os.mkdir(os.path.join(dir_csv,'data_files_chb/train')) 
if not os.path.exists(os.path.join(dir_csv,'data_files_chb/test')):
    os.mkdir(os.path.join(dir_csv,'data_files_chb/test')) 

if not os.path.exists(os.path.join(dir_csv,'data_files_chb/test/test_list')):
    os.mkdir(os.path.join(dir_csv,'data_files_chb/test/test_list'))
if not os.path.exists(os.path.join(dir_csv,'data_files_chb/test/test_list_v2')):
    os.mkdir(os.path.join(dir_csv,'data_files_chb/test/test_list_v2'))


if not os.path.exists(os.path.join(dir_csv,'data_files_chb/train/train_list_v2')):
    os.mkdir(os.path.join(dir_csv,'data_files_chb/train/train_list_v2'))

dirname = '/media/datadrive/bsalafian/EEGDataLongDuration'
dir_csv = '/home/baharsalafian'

i = 0

testindx,trainindx=SelectIndx(i,indx,dirname)

load_samples_modified_V2_seperate(dir_csv,data_cat='train',data_list='train_list',shuffle=True,temporal_length=8,temporal_stride=1)

# df_test = pd.read_pickle(os.path.join(os.path.join(dir_csv,'data_files_chb/test/test_list_v2'), 'chb10_12_1.pkl'))

# ### let's combine all samples #######

# x_test = np.array(df_test.iloc[:,1])
# print(len(x_test[0]))
# data_list = load_samples_modified(dir_csv,data_cat='test',data_list='test_list',shuffle=True,temporal_length=8,temporal_stride=1)

# print(len(data_list))
# df = pd.DataFrame(columns=['FileName', 'Label', 'index'])
# for i in range(len(data_list)):
#   print(i)
#   # print(data_list[i][2])
#   x = segment_data(data_list[i][0][0])
#   x = x[data_list[i][2]]
#   # print(x.shape)
#   df = df.append({'FileName': x , 'Label': data_list[i][1],'ind': data_list[i][2]},ignore_index=True)
# df.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_chb/test/test_list'), 'data_list.pkl'))



# print(data_list)

# ReadMatFiles(dirname, dir_csv, trainindx, 'train')

ReadMatFiles(dirname, dir_csv, testindx, 'test')
