# -*- coding: utf-8 -*-
"""Copy of TCN_Example_Bahareh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TcSy2-BXUmAPwJeWSyDy84Wq6-ZWfR-5
"""

from cProfile import label
from distutils.command.bdist import show_formats
import multiprocessing
import os
import sys
from tabnanny import check
from matplotlib import test
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="2"
import tensorflow as tf
import scipy
import h5py
import glob, os
from scipy.io import loadmat,savemat
import math
from keras.models import Model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
import collections
# from parse_label import parse_event_labels
# %matplotlib inline
# from keras.datasets import mnist
from sklearn.metrics import plot_precision_recall_curve,roc_curve,roc_auc_score,auc
from sklearn.metrics import precision_recall_fscore_support,precision_recall_curve
import itertools
from tensorflow import keras
from tensorflow.keras.regularizers import l2, l1_l2
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D, GlobalAveragePooling2D
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,TimeDistributed, GRU,Concatenate
from tensorflow.keras.optimizers import Adam
from keras.layers import BatchNormalization
from keras.utils import np_utils
from keras.layers import Conv1D, GlobalAveragePooling1D,MaxPooling1D,AveragePooling1D
from keras.layers.advanced_activations import LeakyReLU
from keras.preprocessing.image import ImageDataGenerator
from sklearn import preprocessing
from keras import regularizers
from numpy import mean
from numpy import std
from tqdm.auto import tqdm
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from tensorflow.keras.datasets import cifar10
# from keras.optimizers import Adam
# from keras.layers.normalization import BatchNormalization
from keras.utils import np_utils
from keras.layers import Conv1D, MaxPooling1D, ZeroPadding1D, GlobalAveragePooling1D,Bidirectional
from keras.layers.advanced_activations import LeakyReLU
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import LearningRateScheduler
from sklearn import preprocessing
from sklearn.metrics import roc_auc_score
# from keras import regularizers
# from regularizers import l1_l2
from numpy import mean
from numpy import std
import pickle
import re
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.layers import InputLayer
from keras.layers import Input
import time
import gc
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator
import math
import wandb
from wandb.keras import WandbCallback
from collections import deque
from scipy.io import loadmat
import copy

# datagen = ImageDataGenerator(zca_whitening=True)
# from google.colab import drive
# drive.mount('/content/drive')

from keras_tcn import TCN
from SBRNN_Keras import ModelConfig, SBRNN_Detector, ModelConfigTCN
from data_gen_chb import SeizureDataGenerator


def PatientsEDFFile(dirname):

  os.chdir(dirname)
  a=[]
  X=[]
  Y=[]
  b=[]
  c = []
  k=0
  for file in glob.glob("*.pkl"):

    split_file=file.split('.')
    # print(split_file[0])
    split_file2=split_file[0].split('_')
    b.append(split_file2[2]+'_'+split_file2[3]+'_'+split_file2[4]+'_'+split_file2[5])
    a.append(file)
    c.append(split_file[0])

      # print(a)
  # print("this is len of the whole pickle files", len(a))
  return a,b,c




def recall2(y_true, y_pred):

  true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
  possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
  recall_m = true_positives / (possible_positives + K.epsilon())
  return recall_m

def precision(y_true, y_pred):

  true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
  predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
  precision_m = true_positives / (predicted_positives + K.epsilon())
  return precision_m

def AUCPR(y_true, y_pred):

  precision, recall, _ = precision_recall_curve(y_true, y_pred)

  PR1=auc(recall, precision)

  return PR1
# def f1_score(y_true, y_pred):
  # precision_m = precision(y_true, y_pred)
  # recall_m = recall(y_true, y_pred)
  # return 2*((precision_m*recall_m)/(precision_m+recall_m+K.epsilon()))
def f1_score(y_true, y_pred,threshold_shift=0):

  y_pred = K.clip(y_pred, 0, 1)
  # shifting the prediction threshold from .5 if needed
  y_pred_bin = K.round(y_pred + threshold_shift)
  tp = K.sum(K.round(y_true * y_pred_bin)) + K.epsilon()
  fp = K.sum(K.round(K.clip(y_pred_bin - y_true, 0, 1)))
  fn = K.sum(K.round(K.clip(y_true - y_pred, 0, 1)))
  precision1 = tp / (tp + fp)
  recall1 = tp / (tp + fn)
  p = precision1
  r = recall1
  return 2 * ((p * r) / (p + r))

def auc_roc(y_true, y_pred):

  return tf.py_function(roc_auc_score, (y_true, y_pred), tf.double)

def auc_pr(y_true, y_pred):

  return tf.py_function(AUCPR, (y_true, y_pred), tf.double)


def  Conv_BN_Act_Pool(filtNo,filtsize1,filtsize2,input1,activation,PoolSize,l2_size,drop_size):


  conv1 = Conv1D(filtNo,filtsize1,kernel_regularizer=l2(l2_size))(input1)
  conv2 = Conv1D(filtNo, filtsize2,kernel_regularizer=l2(l2_size))(conv1)
  BN=BatchNormalization(axis=-1)(conv2)
  ActFunc=Activation(activation)(BN)
  pool1=MaxPooling1D(pool_size=PoolSize)(ActFunc)
  # out=Dropout(drop_size)(pool1)

  return pool1

def define_CNN(drop_size,initLR):
  l2_size=None
  input_shape=(1000,20)
  denseSize=8
  activation='relu'
  filtsize1=22
  filtNo1=8
  filtsize2=10
  filtNo2=16
  PoolSize=2
  input1 = Input(input_shape)
  model1=Conv_BN_Act_Pool(filtNo1,filtsize2,filtsize1,input1,activation,PoolSize,l2_size,drop_size)
  model2=Conv_BN_Act_Pool(filtNo1,filtsize2,filtsize1,model1,activation,PoolSize,l2_size,drop_size)
  model3=Conv_BN_Act_Pool(filtNo1,filtsize2,filtsize1,model2,activation,PoolSize,l2_size,drop_size)
  model4=Conv_BN_Act_Pool(filtNo2,filtsize2,filtsize1,model3,activation,PoolSize,l2_size,drop_size)
  model5=Conv_BN_Act_Pool(filtNo2,filtsize2,filtsize1,model4,activation,PoolSize,l2_size,drop_size)
  conv6=Conv1D(filtNo1,1)(model5)
  drop1=Dropout(0.25)(conv6)
  flat=Flatten()(drop1)

  denseout = Dense(100)(flat)
  denseout2 = Dense(50)(denseout)
  drop2=Dropout(0.5)(denseout2)
  output = Dense(1, activation='sigmoid')(drop2)
  # define a model with a list of two inputs
  model = Model(inputs=input1, outputs=output)
  model.compile(optimizer=Adam(learning_rate=initLR),loss='binary_crossentropy',metrics=["accuracy",f1_score,precision,recall2])

  return model

def MeanStdVar(mylist):


  ListMean=np.mean(mylist,axis=0)
  ListStd=np.std(mylist)
  ListVar=np.var(mylist)

  return ListMean,ListStd,ListVar


def lr_exp_decay(epoch, lr):
  # k = math.sqrt(2)
  k=2
  if lr>0.00001:
    return lr / k
  else:
    return lr

def create_sub_seq(nn_input, len_ss, labels=None):
    """
    This function creates all sub sequences for the batch
    """
    # print(nn_input.shape)
    n_seq = nn_input.shape[0]

    len_seq = nn_input.shape[1]

    # print(n_seq)
    # print(len_seq)

    n_ss = len_seq - len_ss + 1
    new_labels = []
    if nn_input.ndim == 3:
      new_inp = np.zeros((n_ss*n_seq,len_ss,nn_input.shape[2]))
    elif nn_input.ndim == 4:

      new_inp = np.zeros((n_ss*n_seq,len_ss,nn_input.shape[2], nn_input.shape[3]))

    # print(new_inp.shape)
    if labels is not None:
        dim_labels = labels.shape
        if len(dim_labels) == 2:
            new_labels = np.zeros((n_ss*n_seq, len_ss))

            # print(new_labels.shape)
        elif len(dim_labels) == 3:
            new_labels = np.zeros((n_ss * n_seq, len_ss, dim_labels[2]))
    k = 0
    for i in range(n_seq):
        for j in range(n_ss):
            new_inp[k, :, :] = nn_input[i, j:j + len_ss, :]
            if labels is not None:
                if len(dim_labels) == 2:
                    new_labels[k, :] = labels[i, j:j + len_ss]
                elif len(dim_labels) == 3:
                    new_labels[k, :, :] = labels[i, j:j + len_ss, :]
            k += 1

    return new_inp, n_ss, new_labels

def creat_sub_seq_models(x,y,n_chan,one_sec_samp,tcn,cnn,two_dcnn,gru,len_seq,len_seq_gru):

  if tcn == 1:

    x_new = np.reshape(x, (1, x.shape[0], -1))
    x_new, _,y_new = create_sub_seq(x_new, len_seq, y)
    x_new = np.reshape(x_new, (x_new.shape[0], x_new.shape[1], n_chan, one_sec_samp))
    last_element = y_new.shape[1]

  if cnn == 1:

    x_new = np.reshape(x, (1, x.shape[0], -1))
    x_new, _,y_new = create_sub_seq(x_new, len_seq, y)
    x_new = np.reshape(x_new, (x_new.shape[0], x_new.shape[1], n_chan, one_sec_samp))
    last_element = y_new.shape[1]
    x_new = np.reshape(x_new, (x_new.shape[0], x_new.shape[1]*one_sec_samp,n_chan))
    y_new = y_new[:,last_element-1]
    y_new = np.expand_dims(y_new, axis=1)

  if gru == 1:

    x_new = np.reshape(x_new, (1,x_new.shape[0], x_new.shape[1]*one_sec_samp,n_chan))
    y_new = y_new[:,last_element-1]
    y_new = np.expand_dims(y_new, axis=0)
    x_new, _,y_new = create_sub_seq(x_new, len_seq_gru, y_new)

  if two_dcnn == 1:

    x_new = np.reshape(x, (1, x.shape[0], -1))
    x_new, _,y_new = create_sub_seq(x_new, len_seq, y)
    x_new = np.reshape(x_new, (x_new.shape[0], x_new.shape[1], n_chan, one_sec_samp))
    last_element = y_new.shape[1]
    x_new = np.reshape(x_new, (x_new.shape[0], n_chan, x_new.shape[1]*one_sec_samp))
    y_new = y_new[:,last_element-1]
    y_new = np.expand_dims(y_new, axis=1)

  return x_new, y_new

def find_indices(pid,name):

  index=[]
  for j in range(len(name)):
      index.append([i for i, e in enumerate(pid) if e == name[j]])

  return index

def create_one_sec_sig(pkl, fs):

  sig=pkl.data_preprocess


  # print("this is main signal shape", sig.shape)

  data_len = sig.shape[1]
  sig_segment = []
  for k in range(0, data_len, fs):
    sig_segment.append(sig[:,k:k+fs])
  sig_segment = np.array(sig_segment)

  print("this is sig_seg_one_sec shape",sig_segment.shape)

  seizure_index=[7,8,9,10,11,12,13,14,15,16,17]
  labels = pkl.tse_label_matrix
  tse_split = [1 if ((x==seizure_index).any()) else 0 for x in labels]
  # sig = loadmat(files[i])
  x = sig_segment
  y = tse_split

  return x, y

def make_balance_data(x,y,pkl,desired_intv):
  
  start = pkl.seizure_start
  stop = pkl.seizure_end

  # print("this is seizure start and end", start, stop)
  

  signal_new = x

  seizure_duration = stop - start
  new_sig_start = start - desired_intv * seizure_duration
  new_sig_end = stop + desired_intv * seizure_duration
  if new_sig_start < 0:
      new_sig_start = 0
  if new_sig_end > len(y):
      new_sig_end = len(y)
  original_start_index = int(np.floor(new_sig_start))
  original_stop_index = int(np.floor(new_sig_end))

  no_seizure_duration = original_stop_index - original_start_index - seizure_duration


  return no_seizure_duration

def create_csv_files(dirname,all_img_dir,category_name,index,desired_intv,n_chan,one_sec_samp,len_seq,len_seq_gru,tcn,cnn,two_dcnn,gru):

    main,pid, name_csv = PatientsEDFFile(dirname)

    ind=find_indices(pid,index)
    index_v2=list(itertools.chain.from_iterable(ind))

    # print("this is len of desire file",len(index_v2))
    
    names = []
    size = []

    data=[]
    label=[]
    c = 0
    df = pd.DataFrame(columns=['FileName', 'Label'])
    
    for i in range(len(index_v2)):

      path=os.path.join(dirname,main[index_v2[i]])
      names.append(path)
      # print("name of the file",name_csv[index_v2[i]])
      # print("name of the path ",main[index_v2[i]])
      pkl = pickle.load(open(path , 'rb'))

      x=pkl.data
      fs = one_sec_samp 
      x,y = create_one_sec_sig(pkl, fs)

      ###################### take 3 times before and after of the seizure ####################
      x,y = make_balance_data(x,y,pkl,desired_intv)
      # print("this is 10 times shape of x", x.shape)
      # print(y.shape)
      
      x_new, y_new = creat_sub_seq_models(x,y,n_chan,one_sec_samp,tcn,cnn,two_dcnn,gru,len_seq,len_seq_gru)
      print("this is x new shape", x_new.shape)
      # print("this is y new shape", y_new.shape)
      c = c + x_new.shape[0]
      for j in range(x_new.shape[0]):
        savemat(os.path.join(all_img_dir,name_csv[index_v2[i]]+'_'+str(j)+'.mat'), {"data":x_new[j,:,:]})
        df = df.append({'FileName':name_csv[index_v2[i]]+'_'+str(j), 'Label': y_new[j,:][0]},ignore_index=True)
    df.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_tuh/{category_name}'), f'{category_name}.pkl'))
    print("this is whole length", c)
    # return x_new, y_new
    #   df = pd.DataFrame(columns=['FileName', 'Label', 'index'])
    #   for j in range(x.shape[0]):
    #     # print(type(y[:,j][0]))
    #     df = df.append({'FileName':path , 'Label': y[:,j][0],'index': np.int64(j)},ignore_index=True)
    #   df.to_csv(os.path.join(os.path.join(dir_csv,f'data_files/{category_name}'), f'{name_csv[index_v2[i]]}.csv'))
    # print(len(names))


# def ReadMatFiles(dirname,all_img_dir,dir_csv,ind,category_name):

#   EDF = []
#   EDFFiles = []
#   Name = []
#   EDF,names = PatientsEDFFile(dirname)
#   Name = PatientsName()
#   Xfile=[]
#   Yfile=[]
#   c = 0


#   X=[]
#   Y=[]

#   # print(ind)
#   df = pd.DataFrame(columns=['FileName', 'Label', 'index'])
#   for k in range(len(ind)):


#     csv_name = EDF[ind[k]].split('.')

#     matfile = loadmat(os.path.join(dirname,EDF[ind[k]]))

#     x = matfile['X_4sec']
#     y = matfile['Y_label_4sec']
#     # print(x[0,:,:].shape)
#     y=np.transpose(y)

#     start_idx = np.argmax(y>0)
#     a = y == 1
#     end_idx = len(a) - np.argmax(np.flip(a)) - 1
#     real_y = np.zeros_like(y)
#     real_y[start_idx:end_idx+1] = 1


#     # x, y = segment_data(os.path.join(dirname,EDF[ind[k]]))

#     print("shape of x",x.shape)
#     print("shape of y", real_y.shape)
#     # path = os.path.join(dirname,EDF[ind[k]])


#     for j in range(x.shape[0]):
#       savemat(os.path.join(all_img_dir,csv_name[0]+'_'+str(j)+'.mat'), {"data":x[j,:,:]})
#       df = df.append({'FileName':csv_name[0]+'_'+str(j), 'Label': real_y[j,:][0]},ignore_index=True)
#   df.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_chb_old/{category_name}'), f'{category_name}.pkl'))
#     # c = c + len(df) - 7

#   print("this is the whole length", c)


    # X.append(x)
    # Y.append(y)
    #matfile=loadmat(os.path.join(dirname,EDF[ind[k]]))


  # X = np.concatenate(X,axis=0)
  # Y = np.concatenate(Y,axis=0)
  # Y = Y.T
  # print(X.shape)
  # print(Y.shape)
  # return X, Y

def train_test_split(new_dict,focal_No,gen_No):

    train=[]
    test=[]

    focal_list=new_dict.item()['header_focal']

    generalized_list=new_dict.item()['header_generalized']


    test=[*focal_list[-10:],*generalized_list[-10:]]


    train=[*focal_list[0:focal_No],*generalized_list[0:gen_No]]
    #train=[*focal_list[-5:],*generalized_list[-5:]]

    return train,test


def shuffle_data(samples):

  data = shuffle(samples)
  return data

class My_Custom_Generator(keras.utils.Sequence) :
  
  def __init__(self, image_filenames, labels, batch_size,shuffle) :
    self.image_filenames = image_filenames
    self.labels = labels
    self.batch_size = batch_size
    self.shuffle = shuffle
    self.on_epoch_end()
    
  def on_epoch_end(self):
    # self.indexes = self.list_IDs
    if self.shuffle == True:
      self.image_filenames, self.labels = shuffle(self.image_filenames, self.labels)

  def __len__(self) :
    return (np.ceil(len(self.image_filenames) / float(self.batch_size))).astype(int)
  
  
  def __getitem__(self, idx) :
    batch_x = self.image_filenames[idx * self.batch_size : (idx+1) * self.batch_size]
    batch_y = self.labels[idx * self.batch_size : (idx+1) * self.batch_size]
    # print("this is type of y",type(batch_y))
    # # print("this is dtype of y",dtype(batch_y))
    # print("this is batch y",batch_y)
    x = np.array([loadmat('/home/baharsalafian/tuh_all_images/' + str(file_name)+'.mat')['data'] for file_name in batch_x])
    # print("this is during data generator",idx)
    y = np.array(batch_y)
    # print("this is type of y",type(y))
    # print("this is dtype of y",dtype(batch_y))
    # print("this is batch y",y)
    y = np.expand_dims(y, axis=1)
    

    return x, y


############## train_generator oversample

class My_Custom_Generator_train(keras.utils.Sequence) :
  
  def __init__(self, image_filenames, labels, batch_size,shuffle) :
    self.image_filenames = image_filenames
    self.labels = labels
    self.batch_size = batch_size
    self.shuffle = shuffle
    self.on_epoch_end()

    self.ind_one = [i for i,x in enumerate(self.labels) if x== 1]
    self.ind_zero = [i for i,x in enumerate(self.labels) if x== 0]

    self. x_one = self.image_filenames[self.ind_one]
    self.x_zero = self.image_filenames[self.ind_zero]

    self.y_one = self.labels[self.ind_one]
    self.y_zero = self.labels[self.ind_zero]
    
  def on_epoch_end(self):
    # self.indexes = self.list_IDs
    if self.shuffle == True:
      self.image_filenames, self.labels = shuffle(self.image_filenames, self.labels)

  def __len__(self) :
    return (np.ceil(len(self.image_filenames) / float(self.batch_size))).astype(int)
  
  
  def __getitem__(self, idx) :


    

    selected_idx_one = np.random.choice(len(self.x_one),self.batch_size//2)
 
    batch_x_zero = self.x_zero[idx * self.batch_size//2 : (idx+1) * self.batch_size//2]
    batch_x_one = self.x_one.loc[self.x_one.index[selected_idx_one]]
    

    batch_y_one = self.y_one.loc[self.y_one.index[selected_idx_one]]
    batch_y_zero = self.y_zero[idx * self.batch_size//2 : (idx+1) * self.batch_size//2]
  
    x_one_total = np.array([loadmat('/home/baharsalafian/tuh_all_images/' + str(file_name)+'.mat')['data'] for file_name in batch_x_one])
    x_zero_total = np.array([loadmat('/home/baharsalafian/tuh_all_images/' + str(file_name)+'.mat')['data'] for file_name in batch_x_zero])
    x_total = np.concatenate((x_zero_total,x_one_total),axis=0)
    
    # print("this is during data generator",idx)
    y_one_total = np.array(batch_y_one)
    y_zero_total = np.array(batch_y_zero)

    y_one_total = np.expand_dims(y_one_total, axis=1)
    y_zero_total = np.expand_dims(y_zero_total, axis=1)
    y_total = np.concatenate((y_zero_total,y_one_total),axis=0)

    return x_total, y_total

def PatientsEDFFile_pkl(dirname,dir_csv, fs,desired_intv):

  os.chdir(dirname)
  a=[]
  X=[]
  Y=[]
  b=[]
  c = []
  k=0
  df = pd.DataFrame_pkl(columns=['FileName', 'pid', 'main_no_seizure', 'balance_seizure','seizure'])
  for file in glob.glob("*.pkl"):

    path = os.path.join(dirname,file)
    pkl = pickle.load(open(path , 'rb'))

    sig = pkl.data_preprocess
    start = pkl.seizure_start
    stop = pkl.seizure_end

    seizure_duration = stop - start
    print(sig.shape[1]) 
    noseizure_duration_main = sig.shape[1]//fs  - seizure_duration

    x,y = create_one_sec_sig(pkl, fs)

    noseizure_duration_balance = make_balance_data(x,y,pkl,desired_intv)

    print("this is seizure duration", seizure_duration)
    print("this is main no seizure", noseizure_duration_main)
    print("this is balance no seizure", noseizure_duration_balance)

    split_file = file.split('.')
    # print(split_file[0])
    split_file2 = split_file[0].split('_')
    b.append(split_file2[2]+'_'+split_file2[3])
    a.append(file)
    c.append(split_file[0])

    df = df.append({'FileName':split_file[0], 'pid': split_file2[2]+'_'+split_file2[3],
    'main_no_seizure': noseizure_duration_main, 'balance_seizure': noseizure_duration_balance,
    'seizure': seizure_duration},ignore_index=True)
  
  df.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_tuh'), 'all_patient_info.pkl'))
  df.to_csv(os.path.join(os.path.join(dir_csv,f'data_files_tuh'), 'all_patient_info.csv'))


def generate_file_name_list(dirname,index):

  main,pid, name_csv = PatientsEDFFile(dirname)

  ind=find_indices(pid,index)
  index_v2=list(itertools.chain.from_iterable(ind))
  # x = [i for i in range(len(index_v2))]
  names = []
  for i in range(len(index_v2)):

    names.append(name_csv[index_v2[i]])


  return names

#################### Train the model #############################


modelname = 'CNN_CHB_MIT_new_loader_test2'

indx=range(0,24)

# print(model_tcn)

dir_csv = '/home/baharsalafian'

if not os.path.exists(os.path.join(dir_csv,'data_files_tuh')):
    os.mkdir(os.path.join(dir_csv,'data_files_tuh'))

if not os.path.exists(os.path.join(dir_csv,'data_files_tuh/train')):
    os.mkdir(os.path.join(dir_csv,'data_files_tuh/train'))

if not os.path.exists(os.path.join(dir_csv,'data_files_tuh/test')):
    os.mkdir(os.path.join(dir_csv,'data_files_tuh/test'))



dirname='/home/baharsalafian/TUH_Bahareh_experiment/v1.5.2/raw_seizures'

all_img_dir = '/home/baharsalafian/tuh_all_images'


ModelResults = '/home/baharsalafian/TUH_Bahareh_experiment_dataloader_50patients_train'
new_dict = np.load('/home/baharsalafian/TUH_statistics/All_info.npy', allow_pickle='TRUE')

focal_No = 15
gen_No = 5

modelname = 'CNN_TUH_20_train_20_test'
initLR = 0.0001
num_epochs = 300
batch_size = 256

len_seq = 4
one_sec_samp = 250
num_channel = 20
num_filters = 16

tcn = 0
cnn = 1
two_dcnn = 0
gru = 0
len_seq_gru = 3
desired_intv = 10
l2_size=None
drop_size=0

train, test = train_test_split(new_dict,focal_No,gen_No)

seizure_type_data = collections.namedtuple('seizure_type_data',
                                           ['patient_id', 'seizure_type', 'seizure_start', 'seizure_end', 'data',
                                           'new_sig_start', 'new_sig_end', 'original_sample_frequency','TSE_channels',
                                           'label_matrix', 'tse_label_matrix','lbl_channels','data_preprocess',
                                           'TSE_channels_preprocess','lable_matrix_preprocess','lbl_channels_preprocess',
                                           'data_segment','tse_label_segment','tse_timepoints'])
fs = 250
desired_intv = 10

# PatientsEDFFile_pkl(dirname,dir_csv,fs,desired_intv)

names_test = generate_file_name_list(dirname,test)
names_train = generate_file_name_list(dirname,train)

df = pd.read_pickle(os.path.join(os.path.join(dir_csv,'data_files_tuh'), 'all_patient_info.pkl'))

df_test = df[df['FileName'].isin(names_test)]

df_train = df[df['FileName'].isin(names_train)]

df_test_group = df_test.groupby(['pid'],as_index=False).agg({'FileName':'count','main_no_seizure':'sum', 'balance_seizure':'sum',
                                                        'seizure':'sum'})


df_train_group = df_train.groupby(['pid'],as_index=False).agg({'FileName':'count','main_no_seizure':'sum', 'balance_seizure':'sum',
                                                        'seizure':'sum'})

                                                        
df_group = df.groupby(['pid'],as_index=False).agg({'FileName':'count','main_no_seizure':'sum', 'balance_seizure':'sum',
                                                        'seizure':'sum'})

df_group2 = df.groupby(['pid'],as_index=False).agg({'FileName':list,'balance_seizure':list,
                                                        'seizure':list}) 
df_group2 = df_group2.rename(columns={'FileName':'FileName_list', 'balance_seizure':'balance_seizure_list','seizure':'seizure_list' })  

df_group = df_group.merge(df_group2,how='left', left_on=['pid'],right_on=['pid'])

df_selected = df_group[(df_group.FileName>1) & (df_group.balance_seizure>df_group.seizure)]  
df_selected.sort_values(by=["FileName"], ascending=False, inplace=True)                                                     
df_selected.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_tuh'), 'selected_patient_info_group.pkl'))
df_selected.to_csv(os.path.join(os.path.join(dir_csv,f'data_files_tuh'), 'selected_patient_info_group.csv'))

# df_train_group.to_pickle(os.path.join(os.path.join(dir_csv,f'data_files_tuh'), 'train_15_focal_patient_info_group.pkl'))
# df_train_group.to_csv(os.path.join(os.path.join(dir_csv,f'data_files_tuh'), 'train_15_focal_patient_info_group.csv'))

print(len(df_train))
# create_csv_files(dirname,all_img_dir,'test',test,desired_intv,num_channel,one_sec_samp,len_seq,len_seq_gru,tcn,cnn,two_dcnn,gru)

# create_csv_files(dirname,all_img_dir,'train',train,desired_intv,num_channel,one_sec_samp,len_seq,len_seq_gru,tcn,cnn,two_dcnn,gru)

# start_time = time.time()

# df_train = pd.read_pickle(os.path.join(os.path.join(dir_csv,'data_files_tuh/train'), 'train.pkl'))
